Part 1: Reading PDFS into ONE corpus

In [27]:
from pathlib import Path

RAW_DIR = Path("data/raw")

pdf_files = sorted(RAW_DIR.glob("*.pdf"))

pdf_files

[PosixPath('data/raw/AhoraNacion.pdf'),
 PosixPath('data/raw/BuenGobierno.pdf'),
 PosixPath('data/raw/FuerzaPopular.pdf'),
 PosixPath('data/raw/JuntosPorElPeru.pdf'),
 PosixPath('data/raw/Obras.pdf'),
 PosixPath('data/raw/RenovacionPopular.pdf')]

In [28]:
!pip install pymupdf

Requirement already satisfied: pymupdf in /opt/anaconda3/envs/papersPremier/lib/python3.12/site-packages (1.28.0)

In [29]:
import fitz

In [30]:
doc = fitz.open(pdf_files[0])

doc,len(doc)

(Document('data/raw/AhoraNacion.pdf'), 146)

In [31]:
page = doc[0]

page

page 0 of <data/raw/AhoraNacion.pdf, doc# 15>

In [32]:
text = page.get_text()

print(text)

AHORA NACIÓN
PLAN DE GOBIERNO
(2026-2031)




Firmado Digitalmente por:
MACHUCA CASTILLO NELSON
GIDO FIR 70780350 hard
Fecha: 22/12/2025 20:23:36

In [33]:
text = ""
for page in doc:
    text += page.get_text()
len(text)

373258

In [34]:
print(text[:1000])

AHORA NACIÓN
PLAN DE GOBIERNO
(2026-2031)




Firmado Digitalmente por:
MACHUCA CASTILLO NELSON
GIDO FIR 70780350 hard
Fecha: 22/12/2025 20:23:36
2
















“Todo el poder a las regiones para conquistar los mercados del mundo”




3

ÍNDICE

I.
PRESENTACIÓN .................................................................................................................5
II.
IDEARIO: ..............................................................................................................................7
II.1.
PRINCIPIOS: ............................................................................................................10
II.2.
OBJETIVOS: .............................................................................................................10
II.3.
VISIÓN DEL PARTIDO: ............................................................................................. 11
II.4.
VALORES DE LA AHORA NACIÓN: .........

In [35]:
documents = {}

In [36]:
documents[pdf_files[0].stem] = text

In [37]:
documents.keys()

dict_keys(['AhoraNacion'])

In [38]:
documents

{'AhoraNacion': ' \n \n \n \n \nAHORA NACIÓN \nPLAN DE GOBIERNO  \n(2026-2031) \n \n \n \n \nFirmado Digitalmente por:\nMACHUCA CASTILLO NELSON\nGIDO FIR 70780350 hard\nFecha: 22/12/2025 20:23:36\n2 \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n“Todo el poder a las regiones para conquistar los mercados del mundo” \n \n \n \n \n3 \n \nÍNDICE \n \nI. \nPRESENTACIÓN .................................................................................................................5 \nII. \nIDEARIO: ..............................................................................................................................7 \nII.1. \nPRINCIPIOS: ............................................................................................................10 \nII.2. \nOBJETIVOS: .............................................................................................................10 \nII.3. \nVISIÓN DEL PARTIDO: ............................................................................................. 11 \nII.4. \nVALORES DE LA AHORA NACIÓN: ......................................................................... 11 \nIII. \nVISIÓN DEL PLAN DE GOBIERNO: .............................................................................12 \nIV. \nESTRATEGIAS: .............................................................................................................13 \nIV.1. \nDIMENSIÓN SOCIAL ................................................................................................14 \nIV.1.1. \nPROPUESTAS PARA LA SALUD .....................................................................15 \nIV.1.2. \nPROPUESTAS PARA LA EDUCACIÓN ...........................................................21 \nIV.1.3. \nPROPUESTAS PARA LA VIVIENDA ................................................................27 \nIV.1.4. \nPROPUESTAS PARA EL AGUA Y SANEAMIENTO .........................................31 \nIV.1.5. \nPROPUESTAS PARA EL FOMENTO DEL EMPLEO .......................................35 \nIV.1.6. \nPROPUESTAS PARA INCLUSIÓN SOCIAL.....................................................40 \nIV.1.7. \nPROPUESTAS PARA CULTURA .....................................................................45 \nIV.2. \nDIMENSIÓN INSTITUCIONAL ..................................................................................50 \nIV.2.1. \nPROPUESTAS PARA LA SEGURIDAD CIUDADANA ......................................51 \nIV.2.2. \nPROPUESTAS PARA LA JUSTICIA Y DERECHOS HUMANOS .....................59 \nIV.2.3. \nPROPUESTAS PARA LAS RELACIONES EXTERIORES ...............................63 \nIV.2.4. \nPROPUESTAS PARA LA DEFENSA NACIONAL .............................................69 \nIV.3. \nDIMENSIÓN ECONÓMICA .......................................................................................73 \nIV.3.1. \nPROPUESTAS PARA LA ECONOMÍA .............................................................74 \nIV.3.2. \nPROPUESTAS PARA EL EMPRENDIMIENTO ................................................84 \nIV.3.3. \nPROPUESTAS PARA LA INDUSTRIALIZACIÓN .............................................88 \nIV.3.4. \nPROPUESTAS PARA EL TRANSPORTE.........................................................93 \nIV.3.5. \nPROPUESTAS PARA LA AGRICULTURA ...................................................... 102 \nIV.3.6. \nPROPUESTAS PARA ENERGÍA Y MINAS ..................................................... 110 \nIV.4. \nDIMENSIÓN AMBIENTAL ....................................................................................... 116 \nIV.4.1. \nPROPUESTAS PARA EL CUIDADO DEL MEDIO AMBIENTE ....................... 117 \nV. \nPROPUESTA DE RENDICIÓN DE CUENTAS SOBRE EL CUMPLIMIENTO DEL PLAN DE \nGOBIERNO .............................................................................................................................. 123 \nV.1. \nSISTEMA DE SEGUIMIENTO DEL PLAN DE GOBIERNO .................................... 123 \nVII. \nANEXOS: RESUMEN DEL PLAN DE GOBIERNO ..................................................... 124 \nVI.1. \nDIMENSIÓN SOCIAL .............................................................................................. 124 \nVI.1.1. \nSALUD............................................................................................................ 124 \nVI.1.2. \nEDUCACIÓN .................................................................................................. 125 \nVI.1.3. \nVIVIENDA ....................................................................................................... 126 \n4 \n \nVI.1.4. \nAGUA Y SANEAMIENTO ............................................................................... 127 \nVI.1.5. \nEMPLEO ......................................................................................................... 128 \nVI.1.6. \nINCLUSIÓN SOCIAL ...................................................................................... 129 \nVI.1.7. \nCULTURA ....................................................................................................... 130 \nVI.2. \nDIMENSIÓN INSTITUCIONAL ................................................................................ 131 \nVI.2.1. \nSEGURIDAD CIUDADANA ............................................................................ 131 \nVI.2.2. \nJUSTICIA Y DERECHOS HUMANOS ............................................................ 132 \nVI.2.3. \nRELACIONES EXTERIORES ........................................................................ 133 \nVI.2.4. \nDEFENSA NACIONAL.................................................................................... 135 \nVI.3. \nDIMENSIÓN ECONÓMICA ..................................................................................... 136 \nVI.3.1. \nECONOMÍA .................................................................................................... 136 \nVI.3.2. \nEMPRENDIMIENTO ....................................................................................... 138 \nVI.3.3. \nINDUSTRIALIZACIÓN .................................................................................... 139 \nVI.3.4. \nTRANSPORTES ............................................................................................. 140 \nVI.3.5. \nAGRICULTURA .............................................................................................. 142 \nVI.3.6. \nENERGÍA Y MINAS ........................................................................................ 144 \nVI.4. \nDIMENSIÓN AMBIENTAL ....................................................................................... 145 \nVI.4.1. \nCUIDADO DEL MEDIO AMBIENTE ............................................................... 145 \nVIII. \nDISCLAIMER .............................................................................................................. 146 \n \n \n \n \n5 \n \nI. \nPRESENTACIÓN \n \nAHORA NACIÓN es el nombre del partido que hemos conformado con más de 60,000 afiliados. \nNuestros comités, así como nuestros precandidatos al Congreso de la República, a las \ngobernaciones y consejerías regionales, y a las alcaldías y regidurías provinciales y distritales; \nestán respondiendo al llamado de AHORA NACIÓN. \nSe impone, en consecuencia, profundizar en la esencia, sobre nuestras raíces, y dirigirnos a \nnuestra militancia y a la ciudadanía en general; para dar detalles sobre el concepto o la idea que \nha dado origen a AHORA NACIÓN. \nEl camino de AHORA NACIÓN se inicia con la edición y publicación en marzo de 1991, de la \nRevista APERTURA, que fundamos junto a distintos ciudadanos, y que tuve el honor de dirigir \nentre 1991 y 1996. De la amplia discusión y profuso debate ocurrido al interior de la revista, \nsurgieron los lineamientos ideológicos y programáticos expresados en el libro Modernidad para \nTodos. \nEn el capítulo V de Modernidad para Todos, titulado “Apertura para Modernizar el Perú”, \nsustentamos la tesis de que el Perú ha sido y es más Estado y menos Nación; algo que Jorge \nBasadre, Víctor Andrés Belaúnde, José Carlos Mariátegui y Víctor Raúl Haya de la Torre –pese \na sus muchas y grandes diferencias–, ya nos lo habían advertido al señalar que “no somos \nNación” o que “somos una Nación en formación”. \nNos preguntábamos en 1994, si los peruanos habíamos solucionado el problema que Basadre, \nBelaúnde, Mariátegui y Haya identificaron. Era evidente que no lo habíamos solucionado y que \nlas consecuencias las estábamos pagando y las seguiríamos pagando. Insistíamos, por eso, que \nel Perú es más Estado y menos Nación; que la organización y las formas estatales que \ninstituimos, son formas frías y sin alma, superpuestas encima de una Nación cautiva, ávida de \nexpresarse; que no había ni hay correspondencia entre esas formas frías y muertas y nuestra \nsustancia viva. \n¿A qué nos referimos cuando hablamos de Nación? Como decíamos desde entonces, “Nación \nes alma, espíritu, meta común; es acuerdo en lo fundamental”; o como decía el historiador \nfrancés Ernest Renan, “la Nación es un plebiscito cotidiano”. \nHoy, nuestros planteamientos dejaron de ser sólo un ideal, han servido de inspiración a miles de \nciudadanos, sobre todo a los más jóvenes, para construir un partido político; con comités \nregionales, provinciales y distritales; que crece y se fortalece sobre la base de dos afirmaciones, \nque la militancia estima como políticamente potentes. Primero, la necesidad de “culminar o \nrevitalizar el proceso de formación de la Nación peruana”; y segundo, darle “todo el poder a las \nregiones para conquistar los mercados del mundo”. \nLa primera afirmación se relaciona con la otra tarea histórica a la que se refiere Basadre, la \nnecesidad de cumplir la promesa con la que se fundó el Estado peruano independiente; ser una \nauténtica república de ciudadanos, libres e iguales en derechos, deberes y oportunidades. \nCumplir, en suma, la promesa de la vida peruana: ser una Nación organizada bajo principios \nrepublicanos. \nLa segunda afirmación alude a un profundo y renovado proceso de descentralización, como \ncondición para culminar o revitalizar la formación de la Nación Peruana. La revitalización de la \nNación \nPeruana \nnos \nserá \nesquiva \nnuevamente, \nsino acometemos una profunda \ndescentralización. La expresión “Todo el poder a las regiones para conquistar los mercados del \nmundo”, también alude a la importancia de promover la industrialización global del Perú. Los \nmercados del mundo se conquistan con innovación, con ciencia, con tecnología y también con \nmodelos democráticos superiores. No se trata de dar todo el poder a las regiones en el marco \nde un populismo distribucionista, sino de desarrollar las fuerzas productivas, aprovechando la \nenergía social acumulada, para que el poder regional perdure en el espectro de un pensamiento \nestratégico y competitivo de sus líderes. “Todo el poder a las regiones, para conquistar los \nmercados del mundo” está entonces estrechamente ligado a culminar el proceso de construcción \nde la Nación peruana y cumplir la promesa republicana. \nA ese respecto, considerando el origen y misión histórica de AHORA NACIÓN; a través de la \nSecretaría de Programa y Plan de Gobierno, un equipo de expertos con amplia experiencia en \n6 \n \ndiversos sectores, se han venido reuniendo semana a semana durante varios meses, para \nelaborar las propuestas para el Plan de Gobierno de Ahora Nación. \nEs así que, conforme lo requiere el Jurado Nacional de Elecciones, presentamos al País, nuestro \nPlan de Gobierno, cuya estrategia está basada en las siguientes cuatro dimensiones: \n1. Dimensión Social \n2. Dimensión Institucional \n3. Dimensión Económica \n4. Dimensión Ambiental \nFinalmente, manifiesto mi agradecimiento a quienes directa o indirectamente han contribuido a \nla elaboración del presente de Plan de Gobierno. \n \n \n \nAlfonso López Chau Nava \nPerú, diciembre de 2025 \n \n \n \n7 \n \nII. \nIDEARIO: \n \nAhora Nación convoca a todos los peruanos, fundamentalmente, a la mujer peruana, a los \njóvenes, a los intelectuales, a quienes buscan empleo, a los maestros, a los trabajadores del \ncampo y la ciudad, a los empresarios nacionales (micro, pequeña, mediana y gran empresa: que \ninvierten dentro o fuera del territorio para el Perú), a los oficiales y soldados de nuestras fuerzas \narmadas a ser parte del noble oficio de hacer política, verdadera política. Porque el momento es \nAHORA: ¡AHORA NACIÓN! \nSi crees como nosotros en la verdad, en el trabajo político honesto. Si crees como nosotros en \nla necesidad de comprometerte con la causa común del Perú, te invitamos a hacer política, mejor \npolítica. Te invitamos a trabajar, como seguramente lo están haciendo los militantes honestos de \notros partidos, para devolverle la dignidad a la política, a propiciar un clima de competencia \npolítica sana, a hacer de la política magisterio, porque la cultura es política de espíritu y la política \ndebe ser cultura. \nSi crees como dice el Salmo: "que la justicia engrandece a las naciones", entonces tu camino \nestá con nosotros, tu camino está en AHORA NACIÓN. \n \nUN NUEVO MUNDO AHORA: \nVivimos tiempos de cambio, de competencia aguda. Los problemas globales del planeta afectan \nnuestras estructuras, nuestros hábitos de conducta e inercias a las que nos hemos acostumbrado \nen el viejo orden mundial. La vertiginosa transformación mundial traspasa todas las fronteras, \nafecta todos los niveles de desarrollo, no respeta ideologías y no sabe de estilos de gobierno. \nCon intensidad y velocidad distinta, a todos afecta. \nLa configuración política, militar y económica de la globalización ha sido desplazada. En su lugar \nse instala un escenario menos predecible, competitivo y multipolar en lo tecnológico, financiero \ny militar, que tras el derrumbe del socialismo real y de la globalización exige ser reconsiderado. \nHoy, como nunca en la historia de la humanidad, es visible la relación entre la dinámica de \nacumulación de las potencias, la exportación del capital en cualquiera de sus modalidades y las \nposibilidades de la democracia y la justicia en el rincón más humilde de la tierra. Lo que ocurre \nen el primer vagón del tren afecta al último. \nEsta nueva situación que presenta el mundo no será resuelta sin conflictos. La constitución de \ngrandes bloques regionales y continentales y de articulaciones comerciales, aún más allá de los \nbloques, son respuestas para llevar la competencia, del estrecho marco de los países, a la aguda \ncompetencia por los mercados y zonas de Influencia. Cada día resulta más evidente que la \nsuperación de los problemas económicos de los países desarrollados está atada al desarrollo de \nlos países subdesarrollados. El horizonte de planeación de un país, e incluso de una empresa, \nva más allá de las propias fronteras. \nPara negociar y defender internacionalmente nuestros intereses, tenemos que ampliar nuestro \nmercado interno, tanto como el externo. Para extender el mercado interno, necesitamos \ndefender, sobre nuevas bases, la planta productiva y el empleo. Urge una economía moderna, \nuna economía competitiva que respete e incorpore nuestras características culturales. Pero no \nhay economía moderna, si no hay sociedad moderna. Queremos y podemos tener rumbo, no \ndeseamos ser un país a la deriva en el agitado mar de la economía mundial. No queremos, no \ndebemos y no podemos ser pasivos en el esfuerzo por lograr nuestra propia ubicación mundial. \nQueremos asimilar, no asimilarnos. \n \nIDEAL DE LA NACIÓN PERUANA: \nCotejando aciertos y carencias, diferencias y coincidencias, desde AHORA NACIÓN nos interesa \naportar, sugerir más bien, la necesidad de construir pilares, una base común de pensamiento \nque privilegie lo que nos une, lo que aliente intelectualmente, la afirmación de la nación, su \nfortalecimiento, nos une la búsqueda del patrimonio común de la afirmación de la nación, su \nfortalecimiento. \n \n8 \n \nEn este marco, nuestros clásicos; Víctor Andrés Belaunde, Jorge Basadre, Haya de la Torre y \nJosé Carlos Mariátegui, compartieron el mismo espíritu, coincidieron en la fase, en el tramo, \naunque los "fines" de algunos tuviesen mayor alcance y proyección, y los "medios" de otros \ngeneraran recelo o discrepancia. Todos ellos coincidieron en valorar la nación, en reconocer que \nsomos una nación en formación, en afirmar que sin una solución duradera al problema del Ande \ny la Amazonía, tampoco habrá solución en términos del capitalismo ni en los de socialismo. Pero \namando como amaron al Perú; ninguno de ellos cayó en la ingenuidad de oponer al Perú al \nmundo; al aporte de lo internacional. \nHoy conocemos problemas que no conocieron, hoy disponemos de otros resortes, que la ciencia \ny la tecnología nos proporcionan. Pero el amor al país, su entrega, la angustia por sus problemas, \nsu pasión limpia por la política es un legado invalorable. El problema en el que todos ellos \ncoincidieron sigue siendo un mandato. \nEl Perú, por eso, es más Estado y menos nación. Nación es alma, espíritu, meta común: es \nacuerdo en lo fundamental. Llamar a la modernidad y a trabajar por su unidad en ninguna parte \nha significado no reconocer la diversidad y la propia cultura, Porque unidad no es unanimidad, \nimplica por el contrario diversidad. \n \nIDENTIDAD NACIONAL: \nLa heterogeneidad cultural es la fuente de nuestro carácter único como sociedad: tenemos, \nparadójicamente, una cultura común de tipo multicultural. Por eso, si queremos que el Perú logre \nsu modernización con identidad nacional, se requiere que todos sus individuos y grupos \nculturales, cualesquiera que sean su religión, cultura o clase estén convencidos de que están \ntomando parte en la edificación del país y sean participes de su éxito o fracaso como nación. \nSer una economía y sociedad moderna exige cambiar. Pero no hay cambio auténtico y duradero \nsin instituciones ni hay modernidad, sin respeto a la identidad nacional y a la cultura. Promover \ncambios profundos en el Estado, la economía y la sociedad, sin Instituciones, es tradicional, \npatrimonial, es aventura que conduce al vacío, o a la agotada relación carismática. La historia \ndel Perú ya ha dado ejemplos de esta práctica. \nAhora Nación asume que no hay cambio posible si ésta no asume la energía positiva de nuestra \nheterogeneidad, Heterogéneas eran las fuerzas que lucharon por la Independencia. \nHeterogéneas las fuerzas de Cáceres. Heterogénea es nuestra nacionalidad en formación, \nnuestra geografía y nuestra producción. Con la heterogeneidad de fuerzas el cambio se hace \nvirtud y obtiene perspectivas. \nAhora Nación asume valores de la tradición y modernidad para beneficio del país. En lo primero \nafirmamos la Nación, a través de los valores de disciplina, laboriosidad y de trabajo comunitario. \nPor lo segundo se rescata la eficiencia, la competitividad y la productividad, en una relojería que \narticula democracia y acumulación, economía y política; no de espaldas, sino de cara al Perú. \n \nESTADO, ECONOMÍA Y SOCIEDAD: \nHoy, como ayer, persistimos en participar pluralmente, para responder al problema de la crisis de \nlos partidos y a los aparentes dilemas entre globalización y afirmación nacional, entre identidad \ny diversidad, entre Estado, individuo y sociedad, entre identidad y modernidad, entre Estado y \nmercado, entre desarrollo hacia fuera y desarrollo hacia dentro, entre la competitividad de la \nempresa y la competitividad de la nación, entre acumulación y democracia, y entre economía y \npolítica. Todos ellos, a nuestro juicio, susceptibles de expresarse en el acuciante desafío de la \nhumanidad: Justicia y libertad. \nPara negociar y defender internacionalmente nuestros intereses, tenemos que ampliar nuestro \nmercado interno, tanto como el externo. Para extender el mercado interno, necesitamos \ndefender, sobre nuevas bases, la planta productiva y el empleo. Urge una economía mode

In [39]:
documents = {}

for pdf in pdf_files:
    doc = fitz.open(pdf)

    text = ""

    for page in doc:
        text += page.get_text()

    documents[pdf.stem] = text

In [40]:
documents.keys()

dict_keys(['AhoraNacion', 'BuenGobierno', 'FuerzaPopular', 'JuntosPorElPeru', 'Obras', 'RenovacionPopular'])

In [41]:
for party, text in documents.items():
    print(party, len(text))

AhoraNacion 373258
BuenGobierno 221197
FuerzaPopular 327610
JuntosPorElPeru 215489
Obras 40765
RenovacionPopular 51803

In [42]:
 for pdf in pdf_files:
    doc = fitz.open(pdf)
    print(pdf.stem, len(doc))

AhoraNacion 146
BuenGobierno 98
FuerzaPopular 138
JuntosPorElPeru 74
Obras 27
RenovacionPopular 25

In [43]:
import pandas as pd

corpus = (
    pd.DataFrame.from_dict(documents,
                           orient="index",
                           columns=["text_raw"])
      .reset_index(names="party")
)

In [44]:
corpus

               party                                           text_raw
0        AhoraNacion   \n \n \n \n \nAHORA NACIÓN \nPLAN DE GOBIERNO...
1       BuenGobierno   \n1 \n \n \n \n \n \n \n \n \n \n \nPARTIDO D...
2      FuerzaPopular   \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n ...
3    JuntosPorElPeru                                                ...
4              Obras   \n1 \n \n \n \nPLAN DE GOBIERNO 2026–2031 \nP...
5  RenovacionPopular   \n1 \n \n  \n \n  \n  \n \nPLAN DE GOBIERNO  ...

In [21]:
corpus["n_characters"] = corpus["text_r"].str.len()

In [22]:
corpus[["party", "n_characters"]]

               party  n_characters
0        AhoraNacion        373258
1       BuenGobierno        221197
2      FuerzaPopular        327610
3    JuntosPorElPeru        215489
4              Obras         40765
5  RenovacionPopular         51803

In [23]:
corpus["n_words"] = corpus["text"].str.split().str.len()
corpus[["party", "n_characters", "n_words"]]

               party  n_characters  n_words
0        AhoraNacion        373258    53720
1       BuenGobierno        221197    28149
2      FuerzaPopular        327610    44266
3    JuntosPorElPeru        215489    30513
4              Obras         40765     5583
5  RenovacionPopular         51803     6868

In [24]:
from pathlib import Path

PROCESSED_DIR = Path("data/processed")
PROCESSED_DIR.mkdir(exist_ok=True)

In [25]:
corpus.to_csv(PROCESSED_DIR / "corpus_raw.csv", index=False)

In [26]:
list(PROCESSED_DIR.iterdir())

[PosixPath('data/processed/corpus_raw.csv')]